// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/dc-to-tsx.mjs from "docs/Rework Design Trackster/Trackster v3 App.dc.html". Do not edit by hand.
import { Fragment } from 'react';
import { css } from '../css';

export function BottomNavView({ vm }: { vm: any }) {
  return (<><nav aria-label="Navigasi utama" style={{"position":"fixed","left":"0","right":"0","bottom":"0","zIndex":"35","background":"var(--card)","borderTop":"1.5px dashed var(--border)","display":"flex","alignItems":"flex-start","padding":"8px 6px calc(8px + env(safe-area-inset-bottom))","boxSizing":"border-box"}}>{(vm.v3tabs ?? []).map((t: any, $i0: number) => (<Fragment key={$i0}><div style={{"flex":"1","display":"flex","justifyContent":"center"}}>{t?.tab ? (<><button onClick={t?.go} aria-current={t?.cur} style={css(`min-width:60px;min-height:52px;border:0;background:transparent;color:${t?.c ?? ''};display:flex;flex-direction:column;align-items:center;gap:3px;font:${t?.fw ?? ''} 11px 'DM Mono',monospace;cursor:pointer;padding:2px`)}><span style={css(`width:52px;height:30px;border-radius:8px;background:${t?.pill ?? ''};display:flex;align-items:center;justify-content:center;transition:background 200ms`)}><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d={t?.d} /></svg></span>{t?.label}</button></>) : null}</div></Fragment>))}</nav></>);
}
