// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/dc-to-tsx.mjs from "docs/Rework Design Trackster/Trackster v3 App.dc.html". Do not edit by hand.


export function MascotTipView({ vm }: { vm: any }) {
  return (<><span style={{"display":"flex"}}>{vm.mascotSm}</span></>);
}
