// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/dc-to-tsx.mjs from "docs/Rework Design Trackster/Trackster v3 App.dc.html". Do not edit by hand.


export function MenuLayerView({ vm }: { vm: any }) {
  return (<><div onClick={vm.closeMenus} aria-hidden="true" style={{"position":"fixed","inset":"0","zIndex":"30"}} /></>);
}
