// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/dc-to-tsx.mjs from "docs/Rework Design Trackster/Trackster v3 App.dc.html". Do not edit by hand.


export function OtherView({ vm }: { vm: any }) {
  return (<><section style={{"background":"var(--card)","borderRadius":"10px","padding":"48px var(--pad)","display":"flex","flexDirection":"column","alignItems":"center","gap":"8px","textAlign":"center"}}><span style={{"fontSize":"17px","fontWeight":"700"}}>Belum masuk batch ini</span><span style={{"fontSize":"14px","color":"var(--text-subtle)","maxWidth":"420px"}}>Halaman ini dirombak di batch berikutnya dengan pola yang sama. Fungsinya tetap sama seperti di aplikasi sekarang.</span></section></>);
}
