// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/dc-to-tsx.mjs from "docs/Rework Design Trackster/Trackster v3 App.dc.html". Do not edit by hand.
import { css } from '../css';

export function PageHeaderView({ vm }: { vm: any }) {
  return (<><header style={{"display":"flex","flexDirection":"column","gap":"2px","marginTop":"-8px","borderBottom":"1.5px dashed var(--border)","paddingBottom":"14px"}}><h1 style={css(`margin:0;font-size:${vm.h1s ?? ''};line-height:${vm.h1l ?? ''};font-weight:800;letter-spacing:-.03em`)}>{vm.pageTitle}</h1><p style={{"margin":"0","fontSize":"15px","color":"var(--text-subtle)"}}>{vm.pageSub}</p></header></>);
}
