// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/dc-to-tsx.mjs from "docs/Rework Design Trackster/Trackster v3 App.dc.html". Do not edit by hand.
import { Fragment } from 'react';
import { css } from '../css';

export function StripView({ vm }: { vm: any }) {
  return (<><div role="tablist" style={{"display":"flex","gap":"6px","overflowX":"auto","margin":"-4px -16px 0","padding":"4px 16px","scrollbarWidth":"none"}}>{(vm.v3strip ?? []).map((c: any, $i0: number) => (<Fragment key={$i0}><button role="tab" aria-selected={c?.on} onClick={c?.go} style={css(`height:34px;padding:0 14px;border:0;border-radius:6px;font:600 14px 'Bricolage Grotesque',sans-serif;cursor:pointer;white-space:nowrap;transition:background 150ms;background:${c?.bg ?? ''};color:${c?.c ?? ''}`)}>{c?.l}</button></Fragment>))}</div></>);
}
