// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/dc-to-tsx.mjs from "docs/Rework Design Trackster/Trackster v3 App.dc.html". Do not edit by hand.
import { css } from '../css';

export function ToastView({ vm }: { vm: any }) {
  return (<><div role="status" style={css(`display:flex;align-items:center;gap:10px;border-radius:10px;background:${vm.subBannerBg ?? ''};padding:10px 10px 10px 14px;font-size:14px;line-height:20px`)}><span style={{"flex":"1"}}>{vm.subBanner}</span><button onClick={vm.closeSubBanner} aria-label="Tutup" className="scp3" style={{"width":"30px","height":"30px","border":"0","borderRadius":"8px","background":"transparent","color":"var(--text-subtle)","display":"flex","alignItems":"center","justifyContent":"center","cursor":"pointer"}}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.25" strokeLinecap="round" aria-hidden="true"><path d={vm.ic?.x} /></svg></button></div></>);
}
