// Generates src/components/v3/views/*.tsx from the Claude Design prototype template.
//   node scripts/dc-to-tsx.mjs
// Source of truth: docs/Rework Design Trackster/Trackster v3 App.dc.html (template = lines 43–1280).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from './dc/parse.mjs';
import { createEmitter } from './dc/emit.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.resolve(here, '../../../docs/Rework Design Trackster/Trackster v3 App.dc.html');
const OUT = path.resolve(here, '../src/components/v3');

const lines = fs.readFileSync(SRC, 'utf8').split('\n');
const start = lines.findIndex((l) => l.startsWith('<div data-rm='));
const end = lines.findIndex((l) => l.startsWith('</x-dc>'));
const tree = parse(lines.slice(start, end).join('\n'));

const attr = (n, k) => (n.attrs.find((a) => a[0] === k) || [])[1];
function find(n, pred) {
  if (n.t !== 'el') return null;
  if (pred(n)) return n;
  for (const c of n.children) { const r = find(c, pred); if (r) return r; }
  return null;
}
const ifNode = (name) => find(tree, (n) => n.tag === 'sc-if' && attr(n, 'value') === `{{ ${name} }}`) || (() => { throw new Error('missing sc-if ' + name); })();

// [file name, selector] — sc-if units are emitted by their children (the routing replaces the gate)
const IF_UNITS = {
  Landing: 'vLanding', Auth: 'vAuth', Wizard: 'vWizard', Sidebar: 'showSide', Coach: 'coachShow', Strip: 'stripShow',
  Me: 'vMe', Analysis: 'vAna', Sources: 'vSrc', Privacy: 'vPriv', Tidy: 'vTidy', Calculator: 'vCalc',
  Dashboard: 'isDash', Today: 'isToday', Weekly: 'isWeekly', Budget: 'isBudget', Income: 'isIncome', Checkin: 'isCheckin',
  Subs: 'isSubs', Goals: 'isGoals', Settings: 'isSettings', Chat: 'isChat', Memory: 'isMemory', SplitList: 'isSplit',
  SplitNew: 'isSplitNew', SplitDetail: 'isSplitDetail', Reports: 'isReports', Other: 'isOther', BottomNav: 'showBottom',
  MascotTip: 'showMascot', MenuLayer: 'anyMenu', Modal: 'hasModal', Pwa: 'pwaOpen',
};

const em = createEmitter();
const holes = {};
fs.mkdirSync(path.join(OUT, 'views'), { recursive: true });

const trim = (s) => s.replace(/^(\{" "\})+/, '').replace(/(\{" "\})+$/, '');

function write(name, body, used) {
  const usesFragment = body.includes('<Fragment');
  const usesCss = body.includes('css(');
  const usesMascot = body.includes('<TrackMascot');
  const usesNoop = body.includes('noop');
  const imp = [
    usesFragment ? "import { Fragment } from 'react';" : '',
    usesMascot ? "import { TrackMascot } from '../TrackMascot';" : '',
    usesCss || usesNoop ? `import { ${[usesCss && 'css', usesNoop && 'noop'].filter(Boolean).join(', ')} } from '../css';` : '',
  ].filter(Boolean).join('\n');
  const src = `// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/dc-to-tsx.mjs from "docs/Rework Design Trackster/Trackster v3 App.dc.html". Do not edit by hand.
${imp}

export function ${name}View({ vm }: { vm: any }) {
  return (<>${body}</>);
}
`;
  fs.writeFileSync(path.join(OUT, 'views', `${name}View.tsx`), src);
  holes[name] = used;
}

for (const [name, cond] of Object.entries(IF_UNITS)) {
  const n = ifNode(cond);
  const body = trim(em.inner(n, null));
  write(name, body, em.takeHoles());
}

// non-sc-if units
const topbar = find(tree, (n) => n.tag === 'div' && n.line && attr(n, 'style') === 'display:flex;justify-content:space-between;align-items:center;gap:8px;min-height:48px');
const header = find(tree, (n) => n.tag === 'header' && /border-bottom:1\.5px dashed/.test(attr(n, 'style') || '') && n.line > 100);
const toast = find(tree, (n) => n.tag === 'div' && attr(n, 'role') === 'status');
const mainInner = find(tree, (n) => n.tag === 'main');
const nonIf = new Map();
for (const [name, n, parent] of [['Topbar', topbar, null], ['PageHeader', header, null], ['Toast', toast, null]]) {
  nonIf.set(n, name);
  if (!n) throw new Error('missing ' + name);
  const body = trim(em.node(n, parent));
  write(name, body, em.takeHoles());
}
void mainInner;

// the shell skeleton: same tree, every unit replaced by its generated view
const replace = new Map(nonIf);
for (const [name, cond] of Object.entries(IF_UNITS)) replace.set(ifNode(cond), name);
em.setReplace(replace);
const treeBody = em.node(tree.children[0], null);
em.takeHoles();
const names = [...replace.values()].sort();
fs.writeFileSync(path.join(OUT, 'V3Tree.tsx'), `// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/dc-to-tsx.mjs — shell skeleton of the prototype with every screen swapped for its generated view.
${names.map((n) => `import { ${n}View } from './views/${n}View';`).join('\n')}
${treeBody.includes('css(') ? "import { css } from './css';" : ''}

export function V3Tree({ vm }: { vm: any }) {
  return (<>${treeBody}</>);
}
`);

fs.writeFileSync(path.join(OUT, 'pseudo.css'), `/* GENERATED by scripts/dc-to-tsx.mjs — hover/active/focus rules from the prototype's style-* attributes */\n${em.pseudoCss()}`);
fs.writeFileSync(path.join(OUT, 'holes.json'), JSON.stringify(holes, null, 2));
console.log('units:', Object.keys(holes).length, 'distinct vm keys:', new Set(Object.values(holes).flat()).size);
